### ISSUE TITLE
Copy transcript to clipboard

### ISSUE THREAD

**Issue by doanandy9511** [Lessica/TrollRecorder#105]
**Describe the bug**
When initially generating the transcript, it will successfully copy the entire transcript. But when you want to go back to a recording and copy it again, it will have nothing in the clipboard.

**To Reproduce**
1. Go to any recording with generated transcript. 
2. Click on Transcript (to the left of the 3 dots).
3. Click Copy Transcript button in the top right. 
4. Paste and verify

**Expected behavior**
Transcript would successfully be copied to clipboard.

**Please complete the following information:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.1.1
 - Version 2.11 Build 509

**Comment by Lessica** [comment]
Confirmed. Will be fixed in the next version.

**Comment by Lessica** [comment]
Fixed in [v2.12-516](https://github.com/Lessica/TrollRecorder/releases/tag/v2.12-516)
