### ISSUE TITLE
中文（台灣）語音問題

### ISSUE THREAD

**Issue by Peter1234567899** [Lessica/TrollRecorder#106]
旁白中下載 中文（台灣）的（Siri聲音1）以及（Siri聲音2）都無法成功使用，套用後出來的聲音都是預設的（美佳）

 - Device: iPhone SE 2020
 - OS: iOS 16.5
 - Version 2.11

**Comment by Lessica** [comment]
Fixed in [v2.12-516](https://github.com/Lessica/TrollRecorder/releases/tag/v2.12-516)
