### ISSUE TITLE
已备份数据是否支持恢复至列表？

### ISSUE THREAD

**Issue by Phyday** [Lessica/TrollRecorder#108]
**您的功能请求是否与问题相关？请描述。**
手机重置后，重新安装巨魔版录音机，已购会恢复，但备份至icloud的音频未找到恢复位置，请问支持恢复吗？

**Comment by Lessica** [comment]
你指的是：**iCloud 云备份** 还是 **iCloud 云盘**？

**Comment by Lessica** [comment]
智能云归档 **iCloud 云盘** 并不是 “备份” 功能。它的作用是按月单向归档。

**Comment by Phyday** [comment]
了解了，现在确实是云存档，没开icloud备份
