### ISSUE TITLE
CLI crashes when using speaker output

### ISSUE THREAD

**Issue by BomberFish** [Lessica/TrollRecorder#11]
![IMG_2077](https://github.com/Lessica/TrollRecorder/assets/87151697/cec59974-dfd3-40f7-9faa-d20a0b5a73b6)
When I use the CLI to record system audio, it fails to start with the error code `-66628`. This error does not occur when recording microphone audio.

**Comment by BomberFish** [comment]
For context, my device is an iPhone Xʀ running iOS 17.0.0.

**Comment by enty8080** [comment]
Same thing - #5

Author just closed this issue, I think they either can't fix this or don't care.

**Comment by Lessica** [comment]
These codes are removed on purpose.  
Sorry for the inconvenience. That is an exercise of reverse engineering. ;-)

https://github.com/Lessica/TrollRecorder/blob/ae7722e933c95ba23c28aa4635a17347421fe9bb/cli/recorder.mm#L200-L202
