### ISSUE TITLE
Audio Recorder vs Trollrecorder

### ISSUE THREAD

**Issue by saifulapm** [Lessica/TrollRecorder#12]
Hi, I have Audio Recorder (Limneos). Should I purchase Trollrecorder ? Does Trollrecorder have any extra advantages that AudioRecorder don’t have.. please let me know. Thanks for your awesome work anyway.

**Comment by Lakr233** [comment]
Our products do not directly relate to Audio Recorders, but we are committed to our work. I have not yet used an Audio Recorder, so I cannot offer any comparative advice.

However, our TrollRecorder app is, generally speaking, of high quality, and its basic features are available for free. We encourage you to try it first. If you find it enjoyable, please consider making a purchase. Your support would be greatly appreciated.

**Comment by fbelkadhi** [comment]
Hi, TrollRecorder is much better than AudioRecorder that I used it for several years, with TrollRecorder thanks the fact it is installed through TrollStore, you can use it even without jailbreak, it's much more stable and with one order you can use it on several devices.

**Comment by saifulapm** [comment]
Hi.. I am still using Audio recorder. Also AudioRecorder has a TrollStore version which I am using right now.

Audio Recorder have Dropbox upload feature where audio upload automatically in Dropbox. So if my device stolen, I have my audios. Not sure that Trollrecorder has this feature.
