### ISSUE TITLE
希望添加倍速播放功能

### ISSUE THREAD

**Issue by Siris-Rose** [Lessica/TrollRecorder#15]
首先非常感谢国人团队辛苦的付出！
其次有几个建议，希望可以帮助巨魔录音机变得更好：
1. 希望添加录音倍速播放的功能。
2. 目前录音转录识别的不是很精确，希望可以改进下。
3. 虽然目前不支持MP3编码，有没有什么别的方法可以在手机上将录音转成MP3格式？

**Comment by Lessica** [comment]
1. 暂无这些功能的计划
2. 后续版本会考虑接入更好的识别模型
3. 暂无这些功能的计划
