### ISSUE TITLE
“在其他设备上通话”，没办法正常录音，是蓝色的浮窗，但是点了并不能正常启动录音

### ISSUE THREAD

**Issue by id77** [Lessica/TrollRecorder#16]
有两个iPhone，别的iPhone来电，用装有 TrollRecorder 的设备接听，没办法正常录音。

**Comment by Lessica** [comment]
在最新版本上修复

**Comment by Lessica** [comment]
在最新版本上修复

**Comment by id77** [comment]
最新版又不行了，接到其他设备电话，有悬浮球，但是两个设备录音列表都没该记录。两个设备均装有该App

**Comment by Lessica** [comment]
此功能已从免费试用中移除，将在下个版本「应用程序」选项卡，「电话」当中呈现，开启此功能需要付费。
