### ISSUE TITLE
Recording warning sound change.

### ISSUE THREAD

**Issue by alhaithammsar** [Lessica/TrollRecorder#20]
Hi, I was looking inside the app Files using Filza 
could not find the Recording warning sound to change it, it sounds very bad, I would like to add more clear and American accent one, any idea how to do that, also in future updates, if it’s possible to exclude certain contacts from automatically getting recorded. Thank u

**Comment by taney** [comment]
Thank you and your team so much for your hardwork!

I too, would find this setting very useful. Being able to use a custom warning and also disable it for certain callers would be the icing on the cake. You can make this for premium subscribers only.

**Comment by Lessica** [comment]
The voice is generated by VoiceOver. Not very easy to replace. There's no plan to extend this feature.
