### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#21]
I bought and been having a great time using all the functions, maybe this some of my idea for extending the features :
1. HUD Shortcut toggle (just like trollspeed)
2. HUD Transparancy
3. Force stop recording and mixed it ?  I always got endless “finalizing” process while recording non Callkit, so i have to kill the process (either via ‘killall -9 call-recorder’ or stop service from app) and get the caches after killed it

**Comment by PBF-TECHIE** [comment]
Please also add bulk export for the recordings.

**Comment by 4rtz1z** [comment]
By the way, does using personal automation and assigned when closing app trigger exit hoverball works on your device ?
Idk why triggering exit hoverball doesn't work on me, the open hoverball works fine

device iOS 16.5

oh thanks for being a great dev, nice updates along the week ✌️

**Comment by PBF-TECHIE** [comment]
> Please also add bulk export for the recordings.

Thankyou for adding the feature.👍🏻

**Comment by Lessica** [comment]
All request satisfied in latest version.
