### ISSUE TITLE
Trying to reach Daemon

### ISSUE THREAD

**Issue by PBF-TECHIE** [Lessica/TrollRecorder#22]
TrollRecorder installed since 4 days, but today i checked first three day recordings were present but not of the 4th day. And  when i started the app it also showed trying to reach daemon. Do i have to make sure the app is running in background?? Or something is causing the daemon to stop. ? Please guide to resolve.

**Comment by Lessica** [comment]
No such guide. Install the latest version and check incompatibility by yourself.

**Comment by PBF-TECHIE** [comment]
Ios 17.0. Failure happened once in 4 days.
