### ISSUE TITLE
Unable to reach Daemon

### ISSUE THREAD

**Issue by luckyinsta** [Lessica/TrollRecorder#23]
Its showing the message like this 

" The application setup has encountered an unknown error, the Launch Daemon has not responded to our requests. We are attempting to reconnect, please wait. If the issue persists, you may try reinstalling the application."

I'm using iphone 13 with IOS 17.4
Installed this app with esign Please resolve this issue as soon as possible we are eagerly waiting to use your app 

Thankyou soo much Team

**Comment by Lessica** [comment]
Install with TrollStore.

**Comment by luckyinsta** [comment]
There's no trollstore in ios 17.4,then how can we install it from trollstore

**Comment by Lessica** [comment]
> There's no trollstore in ios 17.4,then how can we install it from trollstore 

Not supported.
