### ISSUE TITLE
悬浮球点击无反应

### ISSUE THREAD

**Issue by tvcbuv** [Lessica/TrollRecorder#28]
机型iPhone 13 pro
系统15.0
TrollStore版本2.0.13
TrollRecorder版本1.5.2-65（此前版本也有此问题）

问题描述：
1.开启始终显示悬浮球-点击悬浮球无任何反应，不弹窗提示开始录音
2.关闭始终显示悬浮球，开启增强通话场景识别-点击悬浮球无任何反应，不弹窗提示开始录音

补充说明：
1.已重新安装并停止服务还原配置，问题依然存在
2.重启手机问题依然存在
3.同时运行了TrollSpeed与Helium，在关闭之后问题依然存在
4.开启自动录音后，拨通电话发现悬浮球会变红但无法点击悬浮球

**Comment by Lessica** [comment]
Known issue on iOS 15.0

**Comment by tvcbuv** [comment]
发行版1.7.2-109在我的手机上悬浮球功能正常了

**Comment by Lessica** [comment]
好的
