### ISSUE TITLE
相同配置下1.4.7会自动录 1.5.8不会 不明白为什么会笃定我未使用过🤣

### ISSUE THREAD

**Issue by baoan7090** [Lessica/TrollRecorder#33]
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/52fc3bda-c524-4e60-8fd3-99a4c67552aa)
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/b94b76df-a0c1-4cd0-88a2-13a9bcef7321)
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/965d3280-8b30-4cbe-964c-65138200dfa9)
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/412b179b-768b-471f-bf9f-739a1e346b47)

![image](https://github.com/Lessica/TrollRecorder/assets/75816928/15885bc4-e2cf-4075-a7b9-87fbb6d6ad4e)
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/37987747-3be3-4703-89c8-2fc0cf9640db)
![image](https://github.com/Lessica/TrollRecorder/assets/75816928/8255bf51-ffee-466d-8f7d-3e115cb16301)

**Comment by Lessica** [comment]
你可以继续用旧版。除去内置的部分常见通话 app 列表，新版需要为三方应用手动开启，不管是否有 CallKit。
