### ISSUE TITLE
Vietnamese translation

### ISSUE THREAD

**Issue by bphucc** [Lessica/TrollRecorder#34]
Hi, I want to contribute the translation for the Vietnamese language for my fellow Vietnamese friends, which file should be modified? Or can you provide me some clue about this? Thanks in advance!

**Comment by Lessica** [comment]
Localization resources are made open-source from now on. You can submit PRs to add your language.

**Comment by Lessica** [comment]
Please have a look at the language resources.  
Create a new PR or send `.strings` files to <82flex@gmail.com>.

**Comment by Lessica** [comment]
Vietnamese translation has been contributed by [@2311WithLuv](https://www.facebook.com/If2019).
