### ISSUE TITLE
Hoverball plus (feature request)

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#38]
Add an option to make it faster ? Right now it takes 5-6 secs before get into idle mode, maybe add options with 1-5 sec range ? 

And could the fold to screen be trigered with a touch to show up ? Rather than slide ? (An options would be better)

Thanks

**Comment by Lessica** [comment]
I would like to consider option 1.

**Comment by 4rtz1z** [comment]
Ok thanks, oh if i may know is there any log that we can inspect when having an "orange" hoverball a.k.a failed recording ? I get quite often after recent updates, had to stop service first

**Comment by Lessica** [comment]
Implemented in the latest version.
