### ISSUE TITLE
Question about the phone call recorder

### ISSUE THREAD

**Issue by dlevi309** [Lessica/TrollRecorder#4]
I was wondering if you plan to add the phone call recording code to the main repo at any point? I was looking forward to there *finally* being an open source implementation of it somewhere 😅 either way, thank you :)

**Comment by Lessica** [comment]
I did reverse engineering to AudioRecorder XS by @limneos.

😅 I think we should ask him if he is willing to share it with us.

**Comment by dlevi309** [comment]
I think it’s fair game, but I am admittedly a little bias 😅 looking forward to this repos progress either way! cheers
