### ISSUE TITLE
Verify License Failed having trollstore and JB

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#40]
I bought the trollstore version and used it, when JB version released i bought it again and install it, but couldn't verify the license using the JB
![IMG_5979](https://github.com/Lessica/TrollRecorder/assets/15857763/3f0a29d6-e593-45a1-bcb4-974c848a5c4a)

**Comment by Lessica** [comment]
Try again. The license server is recovered.
