### ISSUE TITLE
列表的SIM卡别名显示不全

### ISSUE THREAD

**Issue by id77** [Lessica/TrollRecorder#41]
SIM卡别名是4位阿拉伯数字，点进去是全的，外面只有1个数字
![262A34F0-5073-4E8B-A05E-3B8441E3AA0A](https://github.com/Lessica/TrollRecorder/assets/9592236/e2c078a1-0c60-425e-9bed-7f7a007eede6)

**Comment by Lessica** [comment]
Fixed in the latest version.

**Comment by Lessica** [comment]
能分辨就行了，显示那么全干啥

**Comment by id77** [comment]
> 能分辨就行了，显示那么全干啥

都是以手机号后4位命名的，所以前面数字一样就没办法分辨了。两个手机，4个手机号。

**Comment by Lessica** [comment]
爱莫能助。
