### ISSUE TITLE
验证一直失败

### ISSUE THREAD

**Issue by amobaishi** [Lessica/TrollRecorder#43]
官方提示的各种情况都试过了 还是一直验证失败

**Comment by Lessica** [comment]
再查，不要太过自信。不然你就只剩退款一条路了哈。

**Comment by amobaishi** [comment]
我现在用和别人拼车的巨魔版，登录拼车的账号，验证是没问题的。

**Comment by Lessica** [comment]
将 Havoc 订单号发送到 <82flex@gmail.com>，每个月处理一次退款。
