### ISSUE TITLE
Mixer & combiner 具体都有哪些选项可供选择

### ISSUE THREAD

**Issue by dinaau** [Lessica/TrollRecorder#47]
付费功能里的，
combined mode
mixer file format
mixer audio format
mixer sample rate
audio compression 

可以把上面每个选项截图看下吗？

**Comment by Lessica** [comment]
![IMG_0600](https://github.com/Lessica/TrollRecorder/assets/5410705/120a8d50-5234-4341-aefe-732a5c5ee622)

- File format: m4a, caf, wav (pcm only)
- Audio format: aac, pcm
- Sample rate: 8k, 22k, 44k
