### ISSUE TITLE
[fail] AudioQueueStart (-66628)

### ISSUE THREAD

**Issue by enty8080** [Lessica/TrollRecorder#5]
Hello, @Lessica 

Amazing project. However, `recorder` CLI fails on [this line](https://github.com/Lessica/TrollRecorder/blob/59a9b1d7d447a4bbb0877c9dae42963ff66cc39f/cli/recorder.mm#L224) for my device.

**iPhone:** XS, iOS 16.3.1 with TrollStore (no jailbreak)

I was running your CLI tool through the Filza's fish shell. I used these commands to compile and sign the executable (I don't have Theos, so needed to do this manually):

```
$ clang -x objective-c -fobjc-arc -Iinclude cli/recorder.mm -o recorder -isysroot /Users/felix/Desktop/iOS-SDKs/iPhoneOS15.6.sdk -framework Foundation -framework AVFAudio -framework AudioToolbox -framework AVFoundation
$ ldid -Scli/recorder.plist recorder
$ ct_bypass -i recorder -o recorder -r
$
```

This is the output of iPhone:

```
$ ./recorder mic test.mp3
2024-02-09 20:05:08.916 recorder[425:18980] AudioQueueStart (-66628)
2024-02-09 20:05:08.917 recorder[425:18980] _RecorderStart (-66628)
$
```

Looking forward for your reply.

Kind regards,
Ivan Nikolskiy (@enty8080)

**Comment by Lessica** [comment]
I have no idea with your build environment, especially `ct_bypass`. Use `theos` and try again.

**Comment by BomberFish** [comment]
> 1. I have no idea with your build environment, especially `ct_bypass`. Use `theos` and try again.
> 2. Note that the public version of `recorder` is not functional when making a phone call. See https://github.com/Lessica/TrollRecorder/blob/59a9b1d7d447a4bbb0877c9dae42963ff66cc39f/cli/recorder.mm#L200
> 3. Note that `.mp3` encoding is not natively supported by Apple platforms (decoding is supported). Use `.caf` or `.m4a` instead.

Hi, I have also tried something similar (#11) and am facing a similar problem. I built my copy with theos and made it output to a `.caf` file. I am not using it to record calls, rather just record system audio. Is the source release broken?
