### ISSUE TITLE
Matching Screen Record with Call Record

### ISSUE THREAD

**Issue by stephen-carew** [Lessica/TrollRecorder#53]
Greetings! I just wanted to know if it's possible to implement call recording with screen recording so that what comes out is the screen record bundled with the call recording as well.. it's a long shot but I thought I'd ask. This namely for situations like WhatsApp, FaceTime, And other video call capable apps.

Thank you for your time and such an amazing app!

**Comment by Lessica** [comment]
That’s impossible on TrollStore.
