### ISSUE TITLE
通话录音提示开启功能建议

### ISSUE THREAD

**Issue by icense** [Lessica/TrollRecorder#55]
有没有办法加一个不是全局开启通话录音提示的功能，比如部分人打进来是有通话录音提示，部分人打进来是没有提示的

**Comment by Lessica** [comment]
虽然你发的是中文，但是让人挺难懂的。为了防止其他人没看懂，我翻译一下你说的话。

你说的意思是：

> 能不能改进“播放录音提示”功能，使其只针对 **部分联系人** 播放录音提示？

我的答复是：

> 不能，不想加。
