### ISSUE TITLE
通话过程中，找资料，误打开抖音，会导致录音失败

### ISSUE THREAD

**Issue by id77** [Lessica/TrollRecorder#56]
补充：接听其他设备的通话，不知道是否能解决

**Comment by Lessica** [comment]
不打算解决国内群魔乱舞的 App 互冲的问题。

**Comment by adcco** [comment]
> 不打算解决国内群魔乱舞的 App 互冲的问题。> 不打算解决国内群魔乱舞的 App 互冲的问题。
通话录音时闹钟响了会打断通话录音，这个可以解决吗？
