### ISSUE TITLE
录音文件超级大，建议采用压缩格式保存

### ISSUE THREAD

**Issue by reidmex** [Lessica/TrollRecorder#6]
app挺好用的，感谢大佬，确实用心了！
就是录音用wav格式保存，体积实在太大了，能不能改成mp3或者aac格式保存呢？

**Comment by Siris-Rose** [comment]
确实，果断支持正版了！然后混音器与合并器里可以设置录音保存格式，目前支持wav、caf和m4a，希望可以加入mp3格式的原生支持！
![3401E12B-96EA-4A5C-9070-B3A4857F238A](https://github.com/Lessica/TrollRecorder/assets/51070794/0dd79bbe-a4f8-40aa-8c2c-82eccfdd3703)

**Comment by Lakr233** [comment]
已完成
