### ISSUE TITLE
Record when connected isn't working

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#65]
**Describe the bug**
the recording always start everytime i'm dialing on whatsapp, i've turn on the options and per app setting using default setting

**To Reproduce**
1. Try call on whatsapp
2. The recording will begin immediately eventho isn't connected

**Expected behavior**
It should start recordin when the other answer it, right ?

**Screenshots**
-

**Please complete the following information:**
 - iPhone 13 Pro Max
 - iOS 16.6.1
 - latest version trollrecorder 1.9.6

**Additional context**
-

**Comment by Lessica** [comment]
This feature is only meant for phone calls.

**Comment by 4rtz1z** [comment]
Ok got it, should be mention under the options for better understanding IMO

**Comment by Lessica** [comment]
You are right.
