### ISSUE TITLE
Proposal for an 'Automatic Recording for Specified Apps' Feature in TrollRecorder

### ISSUE THREAD

**Issue by thanhtv69** [Lessica/TrollRecorder#66]
Hello,

I'd like to propose a new feature for the TrollRecorder. Specifically, the 'Automatic Recording for Specified Apps' feature. This would allow users to select certain applications that TrollRecorder would automatically record calls from. For example, if a user wants to record calls from their Phone app on their iPhone, they could simply specify this in the settings of TrollRecorder. Accordingly, TrollRecorder will only record calls made through the selected application. I believe this potential customization option would greatly enhance the app's efficiency and effectiveness in aligning with user needs.

Thank you for considering my suggestion.

**Comment by Lessica** [comment]
You're offline. Keep updated.
