### ISSUE TITLE
Add an option to always show hoverball plus while recording

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#67]
**Is your feature request related to a problem? Please describe.**
Add an option to keep showing hoverball plus while recording while using fold to screen edge.

(I'm always show the hoverball plus with fold to screen edge option, but sometimes i do forgot am i have started the recording or not)

**Describe the solution you'd like**
Add the option

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by Lessica** [comment]
Sadly I would like to close this issue due to a weird reason: too many options.
