### ISSUE TITLE
Cannot record while on hold

### ISSUE THREAD

**Issue by bphucc** [Lessica/TrollRecorder#69]
**Describe the bug**
Hi, when I join a Teams meeting, and then there is another call going to, I hold the Teams meeting and pick up the call, but it turns out that the call is not recorded.

**To Reproduce**
1. Join a Team meeting
2. Get another phone call
3. Press 'Hold and pickup' (I don't remember exactly)
4. When finishing the call isn't recorded

**Expected behavior**
The call must be recorded

**Screenshots**
Not any

**Please complete the following information:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 15.7 (19H12)
 - Version 1.9.7

**Additional context**
None

**Comment by Lessica** [comment]
## Why?

- Previous call is not ended. We can’t stop the previous recording.
- While there are multiple calls, we can’t perform multiple recording at the same time.

**Comment by bphucc** [comment]
Thanks for clarifying, looking for the feature cloud (GDrive, ODrive,...) backup!
