### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by dan3577** [Lessica/TrollRecorder#7]
录音的时候，闹钟响了会断开录音
When recording, the alarm clock will disconnect the recording.

**Comment by che2001-Y** [comment]
录音完后没有提醒通知 录音开始结束没有震动提示 耗电量是否可以进行优化 微信发语音会弹录音浮窗

**Comment by dan3577** [comment]
> 录音完后没有提醒通知 录音开始结束没有震动提示 耗电量是否可以进行优化 微信发语音会弹录音浮窗
> 
> After the recording is finished, there is no reminder to notify the recording starts and ends. There is no vibration warning to indicate whether the power consumption can be optimized

我录音完有通知也有震动，你看看是不是开关没打开

**Comment by che2001-Y** [comment]
有更新是否可以直接覆盖安装 需要拆卸旧版本重新安装新版本吗

**Comment by SHHBEST** [comment]
1. 可以直接覆盖安装，但是会导致小组件黑屏，但到了第二天我的小组件就会回归正常（存疑）
2. 直接重新安装，守护进程程序加载失败，需要挂梯子后可行（国内指点不行，坐标江苏），内容都在，配置都在，添加小组件可正常显示
3.作者大大加油💪💪💪，可以添加一些其他功能类似nice 的，可选其他的App进行录音，和联系人指定人录音
系统: iOS 16.6.1
机型: iPhone13pm





------------------ 原始邮件 ------------------
发件人: che2001-Y ***@***.***&gt;
发送时间: 2024年3月12日 01:02
收件人: Lessica/TrollRecorder ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Lessica/TrollRecorder] Bug反馈 (Issue #7)





 
有更新是否可以直接覆盖安装 需要拆卸旧版本重新安装新版本吗

**Comment by che2001-Y** [comment]
如果不需要开机自动启动 巨魔录音机小组件有必要放在主屏幕吗 不放主屏幕影响通话录音后台吗
