### ISSUE TITLE
Can’t verify license 

### ISSUE THREAD

**Issue by Tzahibo** [Lessica/TrollRecorder#71]
**Describe the bug**
Can’t seem to activate my license since the new version.
Adding a picture, the license bought from havoc using my account.

**To Reproduce**
1. link to account
2.  Click Verify 

**Expected behavior**
Should let me activate my license and use the pro features 

**Please complete the following information:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 17.0
 - Version 1.10.1

**Additional context**
Your recorder is the best thing ever, i hope you can help me resolve this issue. Thanks!
![IMG_0713](https://github.com/Lessica/TrollRecorder/assets/169090618/5819c60b-296d-4562-8a3e-7a2387b540e5)

**Comment by Lessica** [comment]
Already told you what to do next, why not follow the instructions?

**Comment by Lessica** [comment]
View your Havoc account and check your purchase history. You may use the wrong account.

**Comment by Tzahibo** [comment]
I’m sorry, it’s my first time posting here.
Thank you for your answer, i double checked, it’s the correct account. Adding picture.
Still getting the same error.
![IMG_0715](https://github.com/Lessica/TrollRecorder/assets/169090618/a7accd40-45be-41bd-88d9-6c10b4bb76ba)

**Comment by Tzahibo** [comment]
Thanks again for you answer,
Now it fixed, changes default browser back to safari and tried to activate, successfully.
Thank you for you help!

**Comment by Lessica** [comment]
Sorry for the inconvenience.

We will try to force this process to use Safari in next version. And disable Private Browsing automatically.
