### ISSUE TITLE
why TR deletes speaker and microphone channel when doing the force convert ?

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#73]
**Describe the bug**
so i always record using "preserve all channel" but sometimes idk why it failed to create the mixed conversion, so the app show a yellow triangle that instruct user to do the manual "convert now" but why it had to delete the mic and speaker file too ?

**To Reproduce**
1. inspect the caches failed recording folder (it had the each channel caf file and other)
2. do the "convert now"
3. inspect the recording folder (it deletes everyting except mixed audio file)

**Expected behavior**
all the audio from each channel is not broken and it should not deletes it when doing the "convert now" while user using the preserve all channel option

**Screenshots**
1. before
![IMG_6931](https://github.com/Lessica/TrollRecorder/assets/15857763/4b4c4c59-1f69-48b6-9ae0-d07b5357e300)
2. do the convert now
![IMG_6930](https://github.com/Lessica/TrollRecorder/assets/15857763/fa0f9b52-57df-4cf8-873a-198eba422af3)
3. after
![IMG_6932](https://github.com/Lessica/TrollRecorder/assets/15857763/0093e829-bf07-49fe-8e82-90c8d453859f)
4. my configuration
![IMG_6933](https://github.com/Lessica/TrollRecorder/assets/15857763/741409ac-a43d-4ff6-8e9d-05582883783e)

**Please complete the following information:**
 - iPhone 13 Pro Max
 -  iOS 16.5
 - latest trollstore JB

**Additional context**
-

**Comment by Lessica** [comment]
Thank you. This will be fixed soon.

**Comment by 4rtz1z** [comment]
Thank you, you're the best !

**Comment by Lessica** [comment]
Try [v1.12.0](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.0)

**Comment by 4rtz1z** [comment]
> Try [v1.12.0](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.0)

i'll test it and report back
