### ISSUE TITLE
You don't have p.....quit this application and try again

### ISSUE THREAD

**Issue by Jaykurb** [Lessica/TrollRecorder#75]
**Describe the bug**

I have download the app, it is signed but when I open it I get the message "you don't have p...

Quit this application and try again"

**To Reproduce**
1. Open app

**Expected behavior**

1. App to open 

**Screenshots**
![image](https://github.com/Lessica/TrollRecorder/assets/49797976/4e5bcbc2-21b8-4187-b6e9-a2f9ac5a5eb6)

**Please complete the following information:**
 - Device: iPhone 11 Pro Max
 - OS: iOS 17.5.1 
- Version 21F90

**Additional context**

**Comment by 4rtz1z** [comment]
TrollRecorder doesn't support sideloading bro, you need a Trollstrore or Jailbreak, and judge by your iOS which is 17.5.1, it basically impossible

**Comment by Jaykurb** [comment]
Nice one man, thanks for letting me know.
