### ISSUE TITLE
TRCallMonitor Jetsam Event

### ISSUE THREAD

**Issue by Lessica** [Lessica/TrollRecorder#76]
ah sorry because that's the only thing that i got, I always got the setup failed using v1.12.0

the only thing showed under settings - analytics data is this
`  "uptime" : 1200,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 0,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,3",
  "coalitionID" : 1856,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.5",
    "releaseType" : "User",
    "build" : "20F66"
  },
  "captureTime" : "2024-06-16 13:00:26.6442 +0700",
  "incident" : "947EE743-65EC-4787-B86D-F072B04909BC",
  "pid" : 3225,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "385",
  "procLaunch" : "2024-06-16 13:00:24.8984 +0700",
  "procStartAbsTime" : 29507435054,
  "procExitAbsTime" : 29549318324,
  "procName" : "TRCallMonitor",
  "procPath" : "\/private\/preboot\/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221\/dopamine-ngwV6X\/procursus\/Applications\/TRApp.app\/TRCallMonitor",
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "wiki.qaq.trservices",
  "crashReporterKey" : "945b3898f1ba1484f608fdb1ea4886c7966d48ef",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "systemID" : "00008110-00091858222A801E",
  "codeName" : "D64AP",
  "throttleTimeout" : 5,
  "codeSigningID" : "wiki.qaq.trapp",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 838868993,
  "codeSigningValidationCategory" : 1,
  "codeSigningTrustLevel" : 0,
  "basebandVersion" : "2.70.01",
  "exception" : {"codes":"0x6400000009000006, 0x0000000000000000","message":" (Limit 6 MB) Crossed High Water Mark","rawCodes":[7205759403943788550,0],"type":"EXC_RESOURCE","subtype":"MEMORY"},
  "termination" : {"namespace":"JETSAM","flags":2,"code":7},
  "faultingThread" : 1,`

_Originally posted by @4rtz1z in https://github.com/Lessica/TrollRecorder/issues/74#issuecomment-2171074726_

**Comment by 4rtz1z** [comment]
Sorry to brought TrollSpeed here, it seems TrollSpeed had the same problem

> AB4E-E2107FE35179"}
{
  "uptime" : 4500,
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 0,
  "deployVersion" : 210,
  "modelCode" : "iPhone14,3",
  "coalitionID" : 2849,
  "osVersion" : {
    "isEmbedded" : true,
    "train" : "iPhone OS 16.5",
    "releaseType" : "User",
    "build" : "20F66"
  },
  "captureTime" : "2024-06-16 13:56:32.0355 +0700",
  "incident" : "629F9247-FE43-4EC2-AB4E-E2107FE35179",
  "pid" : 8763,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "385",
  "procLaunch" : "2024-06-16 13:52:05.9139 +0700",
  "procStartAbsTime" : 103930063776,
  "procExitAbsTime" : 110316706682,
  "procName" : "TrollSpeed",
  "procPath" : "\/private\/preboot\/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221\/dopamine-ngwV6X\/procursus\/Applications\/TrollSpeed.app\/TrollSpeed",
  "bundleInfo" : {"CFBundleShortVersionString":"1.11.11","CFBundleVersion":"c4b10404","CFBundleIdentifier":"ch.xxtou.hudapp"},
  "storeInfo" : {"deviceIdentifierForVendor":"FA6A44DC-12E6-4576-8955-5B355096A772"},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "ch.xxtou.hudservices",
  "crashReporterKey" : "945b3898f1ba1484f608fdb1ea4886c7966d48ef",
  "wasUnlockedSinceBoot" : 1,
  "isLocked" : 0,
  "systemID" : "00008110-00091858222A801E",
  "codeName" : "D64AP",
  "throttleTimeout" : 5,
  "codeSigningID" : "TrollSpeed.4a886cac.unsigned",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570434305,
  "codeSigningValidationCategory" : 1,
  "codeSigningTrustLevel" : 0,
  "basebandVersion" : "2.70.01",
  "exception" : {"codes":"0x6400000009000006, 0x0000000000000000","message":" (Limit 6 MB) Crossed High Water Mark","rawCodes":[7205759403943788550,0],"type":"EXC_RESOURCE","subtype":"MEMORY"},
  "termination" : {"namespace":"JETSAM","flags":2,"code":7},
  "asi" : {"CoreServices":["LSRecord: resolving _LSRecord_resolve__preferredLaunchArchitecture"]},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":101040,"threadState":{"x":[{"value":60677177328},

**Comment by Lessica** [comment]
The daemon has a lower Jetsam priority in this case. I’m not sure this will be fixed by calling `memorystatus_control`.

**Comment by Lessica** [comment]
@4rtz1z Try [v1.12.1](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.1)

**Comment by 4rtz1z** [comment]
> @4rtz1z Try [v1.12.1](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.1)

will do

**Comment by Lessica** [comment]
I will try opa334's solution. He is a really nice guy. Wait a minute.

**Comment by 4rtz1z** [comment]
> I will try [opa334's solution](https://github.com/Lessica/TrollRecorder/issues/74#issuecomment-2171471151). He is a really nice guy. Wait a minute.

Sure np, you guys the best

**Comment by Lessica** [comment]
I can't re-produce this problem at my side. Please have a try at [v1.12.1-288](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.1).

**Comment by 4rtz1z** [comment]
> Unfortunately, I can't re-produce this problem at my side.
> 
> Please have a try at [v1.12.1-289](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.1) (Same version with different build numbers). It removes `_MSSafeMode=1` and replaces them with `DISABLE_TWEAKS=1`.

it's good now, i'll report again if something comes up again, thanks @Lessica

**Comment by Lessica** [comment]
It's another problem related to my test CI. I'm not going to make it a final release.

**Comment by 4rtz1z** [comment]
got it !

**Comment by 4rtz1z** [comment]
got it !

**Comment by Lessica** [comment]
Fixed in [v1.12.1](https://github.com/Lessica/TrollRecorder/releases/tag/v1.12.1).
