### ISSUE TITLE
integrate actions to SquidGesture Tweak by Squidforce

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#83]
**Is your feature request related to a problem? Please describe.**
eventho TR itself has already have shortcuts support but having it support on Squidgesture actions maybe will make it more fluid in terms of execution time, because it tweaks to tweaks communication. cmiiw

i have asked @lclrc in twitter that he/she will integrate it but haven't talk to @Lakr233 @Lessica.

so i created this request, in hoping this could be integrated soon.

**Describe the solution you'd like**
add actions to squidgesture actions

**Describe alternatives you've considered**
-

**Additional context**
-

thanks you're all great dev !

**Comment by Lakr233** [comment]
We are happy to assist you. However, this version, 1.x.x, of the Troll Recorder is currently in maintenance only mode. With that said, we do not consider adding new features, only critical bug fixes are considered. We will schedule your task if future update planed. Thanks for your feedback.

**Comment by Lessica** [comment]
Not possible until SquidGesture supports dynamic listener. Ask @lclrc for a `libsquidgesture` implementation.
