### ISSUE TITLE
Got a bunch message about duplicate framework in latest v1.18.1

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#87]
**Describe the bug**
got bunch of message log after installing the latest v1.18.1,
would this be problem on usage?

**To Reproduce**
1. install the deb
2. bunch log generated

**Expected behavior**
no error

**Screenshots**
-

**Log**
`Setting up wiki.qaq.trapp.jb (1.18.1-354) ...
objc[19269]: Class DXShortcutsGenerator is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/TweakInject/ADockX.dylib (0x105417370) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Library/PreferenceBundles/DockXPrefs.bundle/DockXPrefs (0x1055c0238). One of the two will be used. Which one is undefined.
objc[19269]: Class DXHelper is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/TweakInject/ADockX.dylib (0x1054172f8) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Library/PreferenceBundles/DockXPrefs.bundle/DockXPrefs (0x1055c02b0). One of the two will be used. Which one is undefined.
objc[19269]: Class DDTTYLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511df78) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062dff68). One of the two will be used. Which one is undefined.
objc[19269]: Class DDTTYLoggerColorProfile is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511dfa0) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062dff90). One of the two will be used. Which one is undefined.
objc[19269]: Class DDOSLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e068) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0008). One of the two will be used. Which one is undefined.
objc[19269]: Class DDASLLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511dc58) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0058). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLoggingContextSet is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511de60) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e00d0). One of the two will be used. Which one is undefined.
objc[19269]: Class DDDispatchQueueLogFormatter is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e338) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0198). One of the two will be used. Which one is undefined.
objc[19269]: Class DDAtomicCounter is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e388) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e01e8). One of the two will be used. Which one is undefined.
objc[19269]: Class DDBufferedProxy is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e298) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0238). One of the two will be used. Which one is undefined.
objc[19269]: Class DDMultiFormatter is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e2e8) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0288). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLog is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e108) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e02d8). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLoggerNode is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e158) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0328). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLogMessage is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e130) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0300). One of the two will be used. Which one is undefined.
objc[19269]: Class DDAbstractLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e220) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e03f0). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLoggerInformation is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e180) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0350). One of the two will be used. Which one is undefined.
objc[19269]: Class DDAbstractDatabaseLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511df28) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0468). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLogFileManagerDefault is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511dcf8) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e04e0). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLogFileFormatterDefault is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511dd70) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0530). One of the two will be used. Which one is undefined.
objc[19269]: Class DDFileLogger is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511ddc0) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0580). One of the two will be used. Which one is undefined.
objc[19269]: Class DDLogFileInfo is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511dd20) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0508). One of the two will be used. Which one is undefined.
objc[19269]: Class DDASLLogCapture is implemented in both /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/Applications/TRApp.app/TRCallMonitor (0x10511e0e0) and /private/preboot/6F5BBBE41E30A250BFFC61F467E385A92280C33D63D82A559968757C2B9D1C4F43FE09537F774590B1834D474E0FE221/dopamine-ngwV6X/procursus/usr/lib/WSVendor.framework/WSVendor (0x1062e0620). One of the two will be used. Which one is undefined.`

**Please complete the following information:**
 - iPhone 13 Pro Max
 - OS: iOS 16.5
 - Version 1.18.1

**Additional context**

**Comment by Lessica** [comment]
It is a jailbreak tweaks' issue, not TrollRecorder's. All tweak developers should make all symbols of their objc classes to be hidden with `__attribute__((visibility("hidden")))`.

**Comment by 4rtz1z** [comment]
ok got it, but this won't break anything on TR ?

**Comment by Lessica** [comment]
Perhaps.
