### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by Deci8BelioS** [Lessica/TrollRecorder#9]
Hi, how are you? 

I have the folder es.lproj with all the files translated to Spanish but I don't know where to send them.

**Comment by Lakr233** [comment]
Send it right here, we will merge it with our private codebase. And you can make a pull request we would love to have your name on the readme page.

**Comment by Deci8BelioS** [comment]
[es.lproj.zip](https://github.com/Lessica/TrollRecorder/files/14546595/es.lproj.zip)

**Comment by Lakr233** [comment]
We have incorporated your translation into the latest version and are truly grateful for your contribution. Your name has been included in the readme file. Thank you.
