### ISSUE TITLE
Trollstore version write plist to /var/jb ?

### ISSUE THREAD

**Issue by 4rtz1z** [Lessica/TrollRecorder#90]
**Describe the bug**
as the title, it's triggered all of my banking apps root detection

**To Reproduce**
1. Open the app
2. A plist file being made with path "/var/jb/var/mobile/Library/Preferences/wiki.qaq.trapp-tweak.plist"

**Expected behavior**
should not touch /var/jb in TS version

**Screenshots**
-

**Please complete the following information:**
 - Device: iPhone 13 Pro Max
 - OS: iOS 16.6.1
 - Version 1.20

**Additional context**
-

**Comment by Lessica** [comment]
Confirmed. Will be fixed in the next version.

**Comment by Lessica** [comment]
Seems fixed in [v1.22-369](https://github.com/Lessica/TrollRecorder/releases/tag/v1.22-369).
