### ISSUE TITLE
最新版nathanLR半越狱打开越狱版的app时闪退

### ISSUE THREAD

**Issue by izyq** [Lessica/TrollRecorder#93]
**Describe the bug**
最新版NathanLR半越狱打开越狱版的TrollRecoder app时闪退，巨魔版本能正常打开

**To Reproduce**
1. 下载arm64deb安装包在sileo中安装
2. 打开trollRecoder

**Expected behavior**
修复bug

**Please complete the following information:**
 - Device: [iPhone 14 Pro Max]
 - OS: [iOS 16.5.1]
 - TrollRecoder Version [2.2-392]
 - NathanLR Version [1.1.2]
 - SystemFiles Version [1.8.2-17]
 
**log**
2024/09/28 04:20:57:108  GetPrimaryBundlePath: Failed to get container URL, error = Error Domain=MCMErrorDomain Code=21 "(null)"
2024/09/28 04:20:57:115  GetPrimaryBundlePath: /var/jb/Applications/TRApp.app
2024/09/28 04:20:57:115  GetPrimaryBundle: NSBundle </private/preboot/77E4298D55077372B0B50669E93633A4690C7DC57AE4FE7166A26700593D62976E172A74F36F2B561AD5D0379BF16DB8/jb/Applications/TRApp.app> (loaded)
2024/09/28 04:20:57:140  XPC service started with listener: <MachXPCListener: 0x1089315a0>
2024/09/28 04:20:57:140  GetSyncLitePath: /private/preboot/77E4298D55077372B0B50669E93633A4690C7DC57AE4FE7166A26700593D62976E172A74F36F2B561AD5D0379BF16DB8/jb/Applications/TRApp.app/TRSyncLite
2024/09/28 04:20:57:141  NOT-TO-BACKUP: Service is disabled.
2024/09/28 04:20:57:141  User defaults or environment changed, wake-up backup service.
2024/09/28 04:20:57:142  NOT-TO-SYNC: Service is disabled.
2024/09/28 04:20:57:142  User defaults or environment changed, wake-up sync service.
2024/09/28 04:20:57:143  TRCallMonitor did start, pid = 3858
2024/09/28 04:20:57:143  Removed all notifications
2024/09/28 04:20:57:143  NOT-TO-SCHEDULE: Backup service is not running.
2024/09/28 04:20:57:143  NOT-TO-SCHEDULE: Sync service is not running.
2024/09/28 04:21:00:149  Audio route changed <Category: (null), Mode: (null), Chat: NO, Route: Speaker, PIDs: (
)>
2024/09/28 04:21:05:922  - [TRUserDefaults reloadFromDisk]
2024/09/28 04:21:08:028  - [TRUserDefaults reloadFromDisk]
2024/09/28 04:21:08:837  - [TRUserDefaults reloadFromDisk]
2024/09/28 04:21:09:355  - [TRUserDefaults reloadFromDisk]
2024/09/28 04:21:10:132  - [TRUserDefaults reloadFromDisk]

**Comment by Lessica** [comment]
NathanLR 不在支持列表。请使用巨魔版本。

**Comment by izyq** [comment]
> NathanLR 不在支持列表。请使用巨魔版本。
其实之前的NathanLR用起来是没有问题的，我更新了才出现闪退的问题
除了APP打开闪退之外，其余功能也是正常使用，真的不考虑修复一下吗

**Comment by Lessica** [comment]
你更新的 NathanLR 闪退，为啥要录音机修复
