### ISSUE TITLE
Add the ability to play custom sounds over the phone?

### ISSUE THREAD

**Issue by KatttTheFemboi** [Lessica/TrollRecorder#96]
**Is your feature request related to a problem? Please describe.**
No, this is just an idea I thought of.

**Describe the solution you'd like**
I thought about how when you activate the call recording warning feature it can play Siri over the line, and thought, what if you were able to play custom sounds over it? And although it's not really related to call recording I still think it could be a cool feature/side project :)

**Describe alternatives you've considered**
I checked if the source code was available so I could try to make it myself, but it wasn't so here I am

**Additional context**
This is probably pretty stupid, but I just thought it could be useful/cool maybe I don't know..

**Comment by Lessica** [comment]
As you said, it's not really related to call recording. We still have some jobs to do, and we won't add this feature to TrollRecorder in the meantime.
